### ISSUE TITLE
Public documentation task list

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#177]
A structure for the public documentation (`/docs`). To be updated.

## Getting started

* [x] Create a new account
* [x] Create a new site
* [x] Create a new page
* [x] Embed that page to a HTML page

## Authentication

* [x] Detailed documentation on signing up/signing in
* [x] Change user information
* [ ] ~~Export user data~~ (wait for feature to be completed)
* [x] Delete user profile

## Sites and pages

* [x] What are sites? What are pages?
* [x] Create new site
* [x] Update site data
* [ ] ~~Export site data~~ (wait for feature to be completed)
* [x] Delete sites
* [x] Create new page
* [x] Update page data
* [ ] ~~Export page data~~ (wait for feature to be completed)
* [x] Delete pages

## Embed comments

* [x] Embed a comment section

## Moderation

* [x] Introduction
* [x] Toggle auto-approval
* [x] Approve a comment
* [x] Delete a comment

## Customisation

* [x] Introduction
* [x] Update the HTML of a comment section

## Public API

* [x] Introduction
* [x] Retrieving comments
* [x] Posting comments
