### ISSUE TITLE
Basic authentication task list

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#49]
* [x] Create new users by ~~email~~, Google and GitHub (and make way for other possible services in the future)
* [x] Users can log in and log out normally
* [x] Users can update basic personal information
* [x] Users can link account to other accounts (Google and GitHub)
* [x] Users can export all personal information stored
* [x] Users can delete the account
* [x] Verbose error handling
* [x] Tests
